service: aws-lambda-java-chrome-example

provider:
  name: aws
  runtime: java11
  profile: serverless-admin
  region: eu-central-1
  timeout: 30
  memorySize: 4096
  lambdaHashingVersion: 20201221

functions:
  invokeChrome:
    image: 547530709389.dkr.ecr.eu-central-1.amazonaws.com/lambda-java-chrome:2
